initial:
    location: [0,0,0]
    orientation: [[1,0,0], [0, 1, 0], [0, 0, 1]] 
    inlierRatio: 0.5
geometry:
    detection: 
        method: 'SIFT'
    descriptor: 'BruteForce'
    featureMatcher : 
        method: 'FlannMatcher'
        configs:
            indexParams:
                algorithm : 0  #FLANN_INDEX_KDTREE = 0
                trees : 5
            searchParams:
                checks : 50
            K : 2
            maxRatio : 0.8
    epipolarGeometry:
        numTrials: 5
        inlierRatio: 0.5
        method: 8    # ('Ransac' or cv2.RANSAC = 8)
        probability :  0.9999
        threshold: 0.8
    triangulation : 
        minDistThresh : 2
        maxRadius : 30
        repErrThresh : 0.5
    pnpSolver:
        method: 'P3P'
        numTrials: 5
        deltaT: 1.2
        minRatio: 0.5
        iterationsCount: 2000
        reprojectionError: 1
        confidence:  0.9999
    bundleAdjustment:
        enable: False
debug:
    plotting :
        features: False
        featureMatches : False
    logging :
        inliersFilterRANSAC: False